spring.application.name=FlowState

spring.datasource.url=jdbc:mysql://localhost:3306/FLOWSTATE_DATABASE

spring.datasource.username=root

spring.datasource.password=mysql

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

jwt.secret=NzQ3YzQzMzQzMzQ3MzI2YjY5NjU2YTY1NjY2NTY0NjQ2NTY1NjQ2YzY1NzY2NTZjNmY3MDZkNjU2ZTc0NzM2NTYzNzI2NTc0NmI2NTc5
jwt.expiration=3600000
